version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/app.env
    environment:
      - RAILS_ENV=production
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/Nobolt_app
    depends_on:
      - chrome
  chrome:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - 4444:4444
      - 5900:5900
  web:
    build:
      context: containers/nginx
    volumes:
      - ./public:/Nobolt_app/public
      - ./tmp:/Nobolt_app/tmp
    ports:
      - 80:80
    depends_on:
      - app