version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/app.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/Nobolt_app
      - ~/.ssh:/root/.ssh
    cpu_quota: 50000
    depends_on:
      - db
      - chrome
  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
  chrome:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - 4444:4444
      - 5900:5900
  web:
    build:
      context: containers/nginx
    volumes:
      - ./public:/Nobolt_app/public
      - ./tmp:/Nobolt_app/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  db-data: