default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: develop
  password: '@Develop99'
  host: <%= ENV.fetch("DB_HOST") { 'db' } %>

development:
  <<: *default
  database: nobolt_app_development

test:
  <<: *default
  database: nobolt_app_test

production:
  <<: *default
  database: nobolt_app_production
  username: nobolt_app
  password: <%= ENV['nobolt_app_DATABASE_PASSWORD'] %>
  socket: /tmp/mysql.sock