default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: develop
  password: '@Develop99'
  host: <%= ENV.fetch("DB_HOST") { 'db' } %>

development:
  <<: *default
  database: nobolt_app_development

test:
  <<: *default
  database: nobolt_app_test

production:
  <<: *default
  host: <%= Rails.application.credentials.rds[:host] %>
  database: <%= Rails.application.credentials.rds[:database] %>
  username: <%= Rails.application.credentials.rds[:username] %>
  password: <%= Rails.application.credentials.rds[:password] %>
  socket: /tmp/mysql.sock